# -*- coding: utf-8 -*-
"""Cliplink_Test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JSLLvNopYnwloQpGurpTEjOjn-DpwmCK
"""

!pip install openai yt-dlp moviepy

import openai
import base64
import json
import os
from moviepy.editor import VideoFileClip
from IPython.display import display
from PIL import Image
import requests



import yt_dlp

# 🔐 OpenAI key
openai.api_key = os.getenv("OPENAI_API_KEY")  # Load from environment variable

def download_instagram_reel(reel_url: str, out_path: str = "reel.mp4"):
    ydl_opts = {
        'outtmpl': out_path,
        'format': 'mp4',
        'quiet': True,
        'noplaylist': True,
    }
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        ydl.download([reel_url])
    return out_path

def extract_frame_base64(video_path: str, t: float = 1.0):
    clip = VideoFileClip(video_path)
    frame_path = "frame.jpg"
    clip.save_frame(frame_path, t=t)
    with open(frame_path, "rb") as f:
        return base64.b64encode(f.read()).decode("utf-8")

def query_gpt4o(b64_image: str, shopper_note: str):
    prompt = f"""
You are a fashion shopping assistant.

A user saw this frame in a reel. Their note is: '{shopper_note}'.

Return a JSON like this:
{{
  "primaryLink": "<exact or very close product, if possible>",
  "altLink": "<close alternate under $60>"
}}

Be concise. If the exact product is unclear, return two close public options with links from Amazon, Asos, or other common sites.
Only output valid JSON.
"""
    response = openai.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are a helpful shopping assistant."},
            {"role": "user", "content": [
                {"type": "text", "text": prompt},
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{b64_image}"}}
            ]}
        ],
        temperature=0.3
    )

    msg = response.choices[0].message.content
    try:
        return json.loads(msg)
    except:
        return {"error": "Could not parse JSON", "raw": msg}

reel_url = input("Enter the Instagram Reel URL: ")
note = input("Describe what you’re looking for in the reel: ")

# ⬇️ Download reel and extract frame
video_path = download_instagram_reel(reel_url)
b64 = extract_frame_base64(video_path)

# 🧠 Get product links
result = query_gpt4o(b64, note)
print(result)

